---
# This tasks will
# - Download the set dynamic modules
# - Unpack the archives
# - Set the variables for each moduel
#     - out dir
#     - configure compile param
#     - other info (archive path, )
- name: Download, unpack, prepare dynamic modules
  when: nginx_compile_install_dynamic_modules is defined and nginx_compile_install_dynamic_modules | length > 0
  vars:
    modules_temp: []
  block:
    - name: Loop modules for preparation
      ansible.builtin.include_tasks:
        file: "{{ role_path }}/tasks/modules/prepare-compile-dynamic-modules/download-prepare-dynamic-module.yml"
      loop: "{{ nginx_compile_install_dynamic_modules }}"
      loop_control:
        label: "{{ item }}"
    - name: Override modules var
      ansible.builtin.set_fact:
        nginx_compile_install_dynamic_modules: "{{ modules_temp }}"
    - name: Set dynamic modules compile params string for all modules
      ansible.builtin.set_fact:
        nginx_install_source_compiled_dynamic_modules: "{{ nginx_install_source_compiled_dynamic_modules | default('') + ' ' + item.configure }}"
      loop: "{{ nginx_compile_install_dynamic_modules }}"

# - name: Check Nginx source or download

# - name: Check Openssl source or download
#   when: nginx_install_source_openssl
# - name: Check perl source or download
#   when: nginx_install_source_pcre
# - name: Check zlib source or download
#   when: nginx_install_source_zlib
